name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Deploy to InfinityFree via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftpupload.net
          username: if0_37999876 # استبدله باسم المستخدم الخاص بـ FTP من InfinityFree
          password: Hmj1Sr4kpt # استبدله بسر الـ FTP
          local-dir: . # المجلد الذي يحتوي على ملفات موقعك
